add TS
dimkamg21/spz_cp_hlukhenkyi pull request #2
Opened 2024-03-14 11:57 UTC by dimkamg21

2024-03-17 19:13 UTC, NULP-KI requested changes
Вимоги які ти розробив є тезовими і не несуть загальної інформації нащо потрібно такий то функціонал робити. Додай загальну описову частину в якій буде загальна інформація про фічю і конкретні речі які дана фіча має забезпечувати. Наприклад,

Для забезпечення високого рівня якості процесу прийняття рішень система має забезпечувати можливість можливість голосового живого захищеного спілкування між абонентами або між групою абонентів. Виклик абонента або групи абонентів має відбувати натисканням кнопки "Виклик". Під час розмови абонети мають мати можливість включити/виключити мікрофон натисканням кнопки "Виключити мікрофон" та завершити розмову натисканням кнопки "Завершити розмову". При цьому функція голосового виклику має задовольняти наступним вимогам:
- Затримка сигналу <1c
- Захищеність за допомогою методів шифрування з закритим та відкритим ключами
- Можливість налаштування необхідності введення паролю
- Використаня стандартних протоколів Інтернет
- Використання захищеного з'єднання
- Можливість ввімкнення/вимкнення фільтрації шумів під час розмови
.......

Тут перша частина - описова. Вказує що і чому розробляється та дає загальне уявлення про фічу. Друга частина містить детальні вимоги до фічі.

Наступне зауваження.
Є певні розділи вимог. Вони мають назви. Якщо ти пишеш вимогу до цього розділу, то збережи назву розділу. Вона є стандартизована і має вживатися як є. без змін.

2024-04-08 14:35 UTC, NULP-KI commented
Вимоги не чіткі. Більше схожі на підказки. я написав приклад вище як їх треба подати. Вимоги мають бути такими що мають враховувати все - від розробки до експлуатації і підтримки.

2024-04-17 13:07 UTC, NULP-KI commented
На сторінці 2 видали все до "Вимоги до структури та функціонування системи". Ці речі є питанням внітрішньої організації роботи. У вимогах вказуються вимоги, які стосуються продукту і його експлуатації, а не розробки.

У тебе багато зустрічається "Це може бути зроблено ..." у вимогах. Це є вимоги, а не обговорення. Має бути чітко написано що очікується. Якщо графік, то графік, якщо меню то меню і які вони мають мати характеристики. Графіки різні буваються. Графіки можливо треба оновлювати. Продумай поведінку, можливості і вид кожної фічі яка вона має бути і опиши їх.

Не закладай вимоги до засобів до розробки. Краще в записці потім обгрунтувати чому саме такі а не інші, ніж закладати в вимоги.

2024-04-28 20:04 UTC, NULP-KI requested changes
Вимоги до системи в цілому мають описувати саме узагальнені вимоги до системи, а не до процесу розробки. Подивіться у приклади що там відображають. Там не говорять про те якими технологіями треба систему реалізувати. Заберіть вимоги до процесів розробки і тестування. У функціональних вимогах не вистачає описової частини. Поставте себе на місце людини яка буде їх реалізувати. Вам би все там було зрозуміло що від вас хочуть щоб ви зробили? Загалом кожна вимога має бути описана описовими реченнями, а от вже конкретні параметри які критичні для замовника мають бути описані конкретними числами тезами, або в тих же описових реченнях якщо їх не багато.

2024-05-10 07:16 UTC, NULP-KI approved these changes
Ще є куди удосконалюватися але наразі нехай буде що є.

2024-05-16 09:17 UTC, dimkamg21 commented
> Ще є куди удосконалюватися але наразі нехай буде що є.

ще добавив опис, але наразі мерджу тожі

2024-05-16 21:11 UTC, NULP-KI approved these changes
Бери за основу і формуй записку.
До кожного пункту вимог треба додати кілька описових речень що наявність даної функції дасть користувачу. Вони ж не просто так додаються.

2024-05-17 09:13 UTC, merged